---
- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - ucso-vault.yml
    - "{{ data_file }}"      
  vars:
    cli:
      username: "{{ admin_username }}"
      password: "{{ admin_password }}"
      transport: cli
 
  tasks:
 
    - name: Configure indiviual port-channel interfaces
      nxos_interface:
        provider: "{{ cli }}"
        host: "{{ item.0.switch }}"
        interface: "{{ item.1 }}"
        state: present
        description: "{{ item.0.desc | default(omit) }}"
        mode: layer2
        admin_state: up
      with_subelements: 
        - "{{ port_data | default([]) }}"
        - port_list
        - skip_missing: yes
    
    - name: Create port-channels on the ToR(s)
      nxos_portchannel:
        provider: "{{ cli }}"
        host: "{{ item.switch }}"
        group: "{{ item.interface | regex_replace('^[^0-9]+([0-9]+)$', '\\1') }}"
        members: "{{ item.port_list }}"
        mode: "{{ item.mode | default('active') }}"
        state: present
        force: true
      with_items: "{{ port_data | default([]) }}"
      when: item.port_list is defined
      
#    - debug: var=command_result
       
    - name: Configure the VPCs on the ToR(s)
      nxos_vpc_interface:
        host: "{{ item.switch }}"
        provider: "{{ cli }}"
        portchannel: "{{ item.interface | regex_replace('^[^0-9]+([0-9]+)$', '\\1') }}"
        vpc: "{{ item.vpc }}"
      with_items: "{{ port_data | default([]) }}"
      when: item.vpc is defined

    - name: Configure the port-channel interface
      nxos_interface:
        host: "{{ item.switch }}"
        provider: "{{ cli }}"
        interface: "{{ item.interface }}"
        state: present
        description: "{{ item.desc | default(omit) }}"
        mode: layer2
      with_items: "{{ port_data | default([]) }}"
      
    - name: Configure the switchport(s)
      nxos_switchport:
        host: "{{ item.switch }}"
        provider: "{{ cli }}"
        interface: "{{ item.interface }}"
        mode: "{{ port_profiles[item.port_profile].mode }}"
        access_vlan: "{{ port_profiles[item.port_profile].access_vlan | default(omit) }}"
        trunk_allowed_vlan_data: "{{ port_profiles[item.port_profile].trunk_allowed_vlan_data | default(omit) }}"
        native_vlan: "{{ port_profiles[item.port_profile].native_vlan | default(omit) }}"
      with_items: "{{ port_data | default([]) }}"

    - name: Add misc commands to the switchport(s)
      nxos_config:
        host: "{{ item.switch }}"
        provider: "{{ cli }}"
        lines: "{{ port_profiles[item.port_profile].commands }}"
        parents: "interface {{ item.interface }}"
      with_items: "{{ port_data | default([]) }}"
      when: item.commands is defined
      register: command_result

