---
- name: Configure domain name on IOS Device
  ios_config:
    lines:
      - "ip domain name {{ dns_domain_name }}"
    provider: "{{ netops_provider }}"
  when: dns_domain_name is defined

- name: Configure name servers on IOS Device
  ios_config:
    lines:
      - "ip name-server {{ item }}"
    provider: "{{ netops_provider }}"
  with_items: "{{ dns_server_list | default([]) }}"

- name: Configure domain name lookup on IOS Device
  ios_config:
    lines:
      - "{{ 'no ' if dns_domain_lookup == false else '' }}ip domain-lookup"
    provider: "{{ netops_provider }}"
